[package]
name = "biors"
version = "0.1.0"
authors = ["mubiquity <connorpane@gmail.com>"]
edition = "2018"

[dependencies]
num-traits = "0.2"
bimap = "0.2"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "sequence"
harness = false